In [1]:
from sklearn.datasets import make_classification
from  sklearn.linear_model import LogisticRegression

In [2]:
# define datasets
x,y=make_classification( n_samples=1000,n_features=10,n_informative=5, n_redundant=5,n_classes=3,random_state=1)

In [3]:
x

array([[ 1.89149379, -0.39847585,  1.63856893, ...,  0.58810926,
        -0.02542177, -0.52835426],
       [ 1.86913773, -0.56336215,  2.03411807, ..., -0.55633   ,
        -0.27340013,  0.72129251],
       [ 1.95259701, -2.83144572,  0.19055535, ..., -0.60957741,
        -2.07750191, -1.75469982],
       ...,
       [ 1.98033054,  1.37228804,  1.67376262, ...,  2.75687956,
        -0.20719842,  0.39299534],
       [-1.54305631, -0.27530218,  0.38744703, ...,  0.72769107,
         0.51983329, -1.92306657],
       [ 1.17970389, -3.3812155 , -0.1498426 , ...,  1.24640268,
        -4.00356845, -3.01027048]])

In [4]:
y

array([1, 0, 1, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0,
       2, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 2, 1,
       1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 1, 2, 2, 2,
       0, 1, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 2, 2,
       1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 0, 1,
       0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0, 2, 1, 2, 0, 0, 1,
       0, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       2, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0, 2,
       0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 2, 2,
       1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2,
       1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1,
       1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 0, 0, 2, 1, 1,

In [5]:
model= LogisticRegression(multi_class="ovr",solver="lbfgs")

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.20,random_state=42)

In [7]:
x_train

array([[ 1.6996658 ,  0.02538366, -0.83658787, ...,  1.29475227,
        -1.26056   ,  0.01001085],
       [-0.31809179, -1.59708983, -0.93941637, ..., -0.24399802,
        -1.14087195, -1.63577652],
       [-1.44568641,  2.35090243, -1.68992829, ..., -0.4410931 ,
         2.94617139,  0.94890677],
       ...,
       [ 1.2434607 , -0.27522163,  1.97095622, ...,  0.96076894,
         0.58347265, -1.33630592],
       [ 2.11062445, -1.23160993,  3.58634974, ...,  0.24849966,
        -1.53366403,  0.36672816],
       [ 1.27331564, -1.15457689, -0.52564804, ...,  0.73643409,
        -1.87397626, -0.81899342]])

In [8]:
y_train

array([1, 1, 2, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 2, 2, 1, 1, 1, 0, 1, 2, 1,
       2, 1, 2, 1, 1, 0, 0, 2, 2, 2, 2, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 0,
       0, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 2, 2, 2, 2, 2, 1, 1, 2, 1, 0, 0,
       2, 1, 2, 2, 1, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 1,
       1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 2, 1, 2, 1, 1, 2, 0,
       0, 1, 2, 0, 0, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 0, 2, 0, 2, 0, 2, 2,
       1, 0, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 0, 0, 2, 0,
       2, 1, 1, 2, 2, 0, 2, 2, 2, 0, 1, 1, 2, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       0, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 2, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 2, 2, 1, 0, 0, 1, 1, 2, 2, 0, 1, 1, 0, 1, 1, 2, 1,
       1, 2, 2, 2, 1, 1, 0, 2, 2, 1, 1, 1, 2, 0, 2, 2, 0, 1, 0, 1, 2, 0,
       2, 0, 1, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2,
       1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 2, 2, 0, 2, 0, 1,
       0, 1, 0, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0, 2, 0,

In [9]:
x_test

array([[-0.71798508, -1.38995287, -1.88281595, ...,  0.01235629,
        -1.04061709, -1.94816896],
       [ 0.58452216, -1.41668082, -2.17506673, ...,  1.85060384,
        -2.73502586, -2.12527924],
       [ 2.95354923, -0.26460278,  0.57407894, ..., -1.00041788,
        -0.60189143,  1.86339253],
       ...,
       [-1.02377699,  0.77312786,  1.69492247, ...,  1.77540726,
        -0.15013218, -0.1982901 ],
       [ 0.8119965 ,  2.03818491,  0.92680834, ...,  2.14003795,
         0.79838627,  0.80964254],
       [-0.34147404,  1.0076694 ,  2.85374386, ...,  0.49932712,
         0.13364908,  1.66752082]])

In [10]:
model.fit(x_train, y_train)

LogisticRegression(multi_class='ovr')

In [11]:
y_pred=model.predict(x_test)

In [12]:
y_pred

array([1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0, 1,
       2, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1,
       0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0,
       2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0])

In [13]:
y_test

array([1, 1, 2, 2, 1, 1, 2, 2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 1, 1, 0, 0, 2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 2, 2, 0, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 0, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 0, 1, 0, 0, 2, 0, 2, 1,
       0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 0, 2, 2,
       2, 1, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2,
       2, 2, 1, 2, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 1, 2,
       2, 0, 0, 2, 2, 1, 2, 2, 1, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2, 1, 0,
       1, 1, 0, 2, 2, 2, 1, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 2,
       1, 2])

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred, y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200



In [16]:
from sklearn.datasets import load_iris

In [18]:
dataset= load_iris()

In [20]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [22]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [23]:
import pandas as pd
import numpy as np

In [24]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [25]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [26]:
df["target"]=dataset.target

In [27]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [28]:
df["target"].unique()

array([0, 1, 2])

In [29]:
x=df.iloc[:,:-1]

In [30]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [31]:
y=df.iloc[:,-1]

In [32]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [33]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.33, random_state=42)

In [41]:
classifier=LogisticRegression(multi_class='ovr', solver='lbfgs')

In [42]:
import warnings
warnings.filterwarnings("ignore")
classifier.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [43]:
y_pred=classifier.predict(x_test)

In [46]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2, 1, 0,
       0, 1, 2, 2, 1, 2])

In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

## checking Accuracy

In [45]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 13  0]
 [ 0  2 16]]
0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.87      1.00      0.93        13
           2       1.00      0.89      0.94        18

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.97      0.96      0.96        50



## Hyperparameter Tuning

In [47]:
from sklearn.model_selection  import GridSearchCV
parameters={ 'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear', 'newton-cg'],
    'multi_class': ['ovr', 'multinomial'],
    'max_iter': [100, 200, 300],
    'tol': [1e-4, 1e-3, 1e-2]}

In [48]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [50]:
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'max_iter': [100, 200, 300],
                         'multi_class': ['ovr', 'multinomial'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg'],
                         'tol': [0.0001, 0.001, 0.01]})

In [51]:
clf.best_params_

{'C': 1,
 'max_iter': 100,
 'multi_class': 'multinomial',
 'solver': 'lbfgs',
 'tol': 0.0001}

In [61]:
classifier=LogisticRegression( C=1,
    max_iter=100,
    multi_class='multinomial',  # Correct parameter value here
    solver='lbfgs',
    tol=0.0001)

In [62]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1, multi_class='multinomial')

In [66]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



## randomized search cv

In [72]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, randint
# Define the hyperparameter distributions to sample from
param_dist = {
    'C': uniform(0.001, 1000),  # Continuous distribution for C
    'solver': ['lbfgs', 'liblinear', 'newton-cg'],
    'multi_class': ['ovr', 'multinomial'],
    'max_iter': randint(100, 500),  # Discrete distribution for max_iter
    'tol': uniform(1e-5, 1e-2)  # Continuous distribution for tol
}

# Create the logistic regression model
logreg = LogisticRegression()

# Use RandomizedSearchCV for hyperparameter tuning
random_search = RandomizedSearchCV(logreg, param_distributions=param_dist, n_iter=10, cv=5, scoring='accuracy', random_state=42)
random_search.fit(x_train, y_train)

# Get the best hyperparameters
best_params = random_search.best_params_
print("Best Hyperparameters:", best_params)

# Train the model with the best hyperparameters on the entire training set
best_logreg = LogisticRegression(**best_params)
best_logreg.fit(x_train, y_train)

# Evaluate the model on the test set
accuracy = best_logreg.score(x_test, y_test)
print("Accuracy on Test Set:", accuracy)

Best Hyperparameters: {'C': 866.1771457749352, 'max_iter': 199, 'multi_class': 'multinomial', 'solver': 'newton-cg', 'tol': 0.00021584494295802446}
Accuracy on Test Set: 0.98
